### ISSUE TITLE
Update docs for v0.2.0

### ISSUE THREAD

**Issue by martincostello** [martincostello/dotnet-bumper#86]
Once v0.2.0 is published to NuGet:

1. Update the demo GIF
2. Add the new output of `--help` in the README
3. Add examples of custom configuration files

```json
{
  "$schema": "https://raw.githubusercontent.com/martincostello/dotnet-bumper/main/dotnet-bumper-schema.json",
  "excludeNuGetPackages": [
    "System.Text.Json"
  ],
  "includeNuGetPackages": [
    "Npgsql"
  ],
  "noWarn": [
    "NU1605"
  ],
  "remainingReferencesIgnore": [
    "tools/*"
  ]
}
```

```yaml
excludeNuGetPackages:
  - System.Text.Json
includeNuGetPackages:
  - Npgsql
noWarn:
  - NU1605
remainingReferencesIgnore:
  - "tools/*"
```
